version: "3.9"
services:

  api:
    image: ${API_IMAGE_NAME}:${API_IMAGE_VER}
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: npm start
    ports:
      - 3001:3001
    volumes:
      - .:/app
      - '/app/node_modules'
    environment:
      DATABASE_HOST: dbsource
    depends_on:
      - dbsource

  dbsource:
    image: mysql:5.7.39
    restart: always
    ports:
      - ${DATABASE_PORT}:3306
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      #MYSQL_ALLOW_EMPTY_PASSWORD: yes
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql:/var/lib/mysql
